[package]
name = "raw-gl-context"
version = "0.1.2"
authors = ["Micah Johnston <micah@glowcoil.com>"]
edition = "2018"
description = "Library for creating an OpenGL context from a RawWindowHandle"
repository = "https://github.com/glowcoil/raw-gl-context"
readme = "README.md"
license = "MIT/Apache-2.0"

[dependencies]
raw-window-handle = "0.3.3"

[target.'cfg(target_os="windows")'.dependencies]
winapi = { version = "0.3.8", features = ["libloaderapi", "minwindef", "windef", "wingdi", "winuser"] }

[target.'cfg(target_os="linux")'.dependencies]
x11 = { version = "2.3", features = ["xlib", "glx"] }

[target.'cfg(target_os="macos")'.dependencies]
cocoa = "0.24.0"
objc = "0.2.7"
core-foundation = "0.9.1"

[dev-dependencies]
gl = "0.14.0"
winit = "0.24"
sdl2 = { version = "0.34", features = ["raw-window-handle", "bundled"] }